### ISSUE TITLE
Update supported images

### ISSUE THREAD

**Issue by dincho** [aeternity/machine-image#27]
- drop 16.04
- add 20.04

**Comment by michalbagrowski** [comment]
https://github.com/aeternity/docker-builder/pull/41

**Comment by michalbagrowski** [comment]
https://github.com/aeternity/docker-builder/pull/42/

**Comment by dincho** [comment]
Why you're linking docker-builder repo ? It has nothing to do ?

**Comment by michalbagrowski** [comment]
https://github.com/aeternity/machine-image/pull/28

**Comment by michalbagrowski** [comment]
@dincho should we add some build on MR to know does new image is building before megre?

**Comment by dincho** [comment]
This is rarely changed, and don't think it's worth the effort. However, as this relies on bootstrap scripts, we should add checks in the infrastructure repo first to make sure it boots 20.04
